### ISSUE TITLE
Extract native modules uniquely

### ISSUE THREAD

**Issue by kylecarbs** [codercom/nbin#4]
https://github.com/codercom/nbin/blob/74da4b366f5c37ea47d83d3e73384e5a3307e00c/node.patch#L108

We don't check if the `.node` file extracted is different than the `.node` file in the binary.

We could do this by hashing the embedded `.node` file, or by checking size for now.

**Comment by code-asher** [comment]
We've decided to keep extracting them each time since it'll only happen once and might be less expensive than hashing anyway.
